### ISSUE TITLE
corrupts menu functionality

### ISSUE THREAD

**Issue by jarrard** [oae/gnome-shell-extensions-sync#1] opened 2019-02-12 04:24 UTC
corrupts menus from being able to search and display on open specific settings.

This happens for Gno-Menu and Applications Menu, probably most others. I tracked it down to this sync extension corrupting the /.config/dconf/user   file.....

**Comment by oae** [comment] 2019-03-25 17:48
Hi @jarrard. I couldn't reproduce the problem. Can you provide the steps for me to test?

**Comment by oae** [comment] 2019-04-02 10:10
I am closing this issue. Please feel free to re-open it.

**Closed by oae** 2019-04-02 10:10 UTC
